//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JennyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Assignments = new HashSet<Assignment>();
        }
    
        public short activityID { get; set; }
        public short projectID { get; set; }
        public string activity_name { get; set; }
        public Nullable<short> staffID { get; set; }
        public Nullable<System.DateTime> pred_start { get; set; }
        public Nullable<System.DateTime> pred_finish { get; set; }
        public Nullable<System.DateTime> act_start { get; set; }
        public Nullable<System.DateTime> act_finish { get; set; }
        public Nullable<int> pred_cost { get; set; }
        public Nullable<int> act_cost { get; set; }
        public Nullable<int> activity_sequence_no { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}
