//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JennyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public short taskID { get; set; }
        public short staffID { get; set; }
        public string task_name { get; set; }
        public short activityID { get; set; }
        public Nullable<System.DateTime> pred_start { get; set; }
        public Nullable<System.DateTime> act_start { get; set; }
        public Nullable<System.DateTime> pred_finish { get; set; }
        public Nullable<System.DateTime> act_finish { get; set; }
        public Nullable<int> pred_cost { get; set; }
        public Nullable<int> act_cost { get; set; }
        public Nullable<short> task_sequence { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
