//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JennyMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public short projectId { get; set; }
        public short clientId { get; set; }
        public string project_name { get; set; }
        public Nullable<System.DateTime> pred_start { get; set; }
        public Nullable<System.DateTime> pred_finish { get; set; }
        public Nullable<System.DateTime> act_start { get; set; }
        public Nullable<System.DateTime> act_finish { get; set; }
        public Nullable<int> pred_cost { get; set; }
        public Nullable<int> act_cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Client Client { get; set; }
    }
}
